# Varables

@PORT=3001

@HOST=http://localhost

@URL={{HOST}}:{{PORT}}

# Dog

### Read request all dogs
GET {{URL}}/dogs HTTP/1.1

### Read name filter by query

GET {{URL}}/dogs?name=Affenpinscher HTTP/1.1