import { DataTypes } from 'sequelize';
import sequelize from '../config/db.config.js';

const temperament = sequelize.define(
	'temperament',
	{
		id: {
			type: DataTypes.INTEGER,
			primaryKey: true,
			autoIncrement: true,
		},
		name: {
			type: DataTypes.ENUM({
				values: [
					'Active',
					'Adaptable',
					'Adventurous',
					'Affectionate',
					'Aggressive',
					'Agile',
					'Alert',
					'Aloof',
					'Amiable',
					'Assertive',
					'Athletic',
					'Attentive',
					'Benevolent',
					'Boisterous',
					'Bold',
					'Bossy',
					'Brave',
					'Bright',
					'Bubbly',
					'Calm',
					'Cat-like',
					'Cautious',
					'Charming',
					'Cheerful',
					'Clever',
					'Clownish',
					'Companionable',
					'Composed',
					'Confident',
					'Cooperative',
					'Courageous',
					'Cunning',
					'Curious',
					'Determined',
					'Devoted',
					'Dignified',
					'Diligent',
					'Docile',
					'Dominant',
					'Dutiful',
					'Eager',
					'Easygoing',
					'Energetic',
					'Even',
					'Excitable',
					'Extroverted',
					'Faithful',
					'Familial',
					'Fast',
					'Fearless',
					'Feisty',
					'Fierce',
					'Friendly',
					'Fun-loving',
					'Gay',
					'Generous',
					'Gentle',
					'Good-natured',
					'Good-tempered',
					'Great-hearted',
					'Happy',
					'Hard-working',
					'Hardworking',
					'Hardy',
					'Independent',
					'Inquisitive',
					'Intelligent',
					'Joyful',
					'Keen',
					'Kind',
					'Lively',
					'Lovable',
					'Loving',
					'Loyal',
					'Merry',
					'Mischievous',
					'Obedient',
					'Opinionated',
					'Outgoing',
					'Patient',
					'People-Oriented',
					'Playful',
					'Powerful',
					'Protective',
					'Proud',
					'Quick',
					'Quiet',
					'Rational',
					'Receptive',
					'Refined',
					'Reliable',
					'Reserved',
					'Respectful',
					'Responsible',
					'Responsive',
					'Rugged',
					'Self-assured',
					'Self-confidence',
					'Self-important',
					'Sensitive',
					'Sociable',
					'Spirited',
					'Spunky',
					'Stable',
					'Steady',
					'Strong',
					'Stubborn',
					'Sturdy',
					'Suspicious',
					'Sweet-Tempered',
					'Tempered',
					'Tenacious',
					'Territorial',
					'Thoughtful',
					'Tolerant',
					'Trainable',
					'Trusting',
					'Trustworthy',
					'Unflappable',
					'Vigilant',
					'Vocal',
					'Watchful',
					'Wild',
					'Willed',
					'Willful',
				],
			}),
			allowNull: false,
			unique: true,
		},
	},
	{ freezeTableName: true, timestamps: false, underscored: true }
);

export default temperament;
